### ISSUE TITLE
extrait du log en live 

### ISSUE THREAD

**Issue by f5swb** [spotnik-ham/gui#10]
Bonjour, 

serait-il possible d'avoir un onglet pour visionner le log en live à l'instar de ce que l'on peut avoir ici :
http://datenport.net/svxrdb/example.html

**Comment by f5nlg** [comment]
Bonjour ,
Pour le log non il est déjà analyser et c'est le dashboard donc ça fera
doublon .
Si on veux le consulter , en ssh avec la commande tail mais on retrouve les
mêmes infos ...
