### ISSUE TITLE
Pas de réactualisation lors du changement de Réseau par DTMF sur la page web du spot

### ISSUE THREAD

**Issue by f4gbv** [spotnik-ham/gui#11]
Lorsque l'on change le Réseau dans la liste déroulante du menu de la page index,
cela se passe bien : la liste se met à jour ainsi que son titre (réseau actif).
Mais quand on le fait via un code DTMF, la page web ne réactualise que la liste et pas le titre (réseau actif)

**Comment by f5swb** [comment]
Bonjour, dans mon cas sous RPI je n'ai aperçu le dashboard qu'une seule fois et depuis plus rien ;)
par contre la commande de changement fonctionne bien :)

**Comment by sonnyp** [comment]
réglé sur master
