### ISSUE TITLE
Network = "conf"   dans /api/svxlink

### ISSUE THREAD

**Issue by f4gbv** [spotnik-ham/gui#12]
Network ne devrait-il pas plutôt contenir "rrf" ou "fon" ou ...  ?

https://hostname/api/svxlink

**Comment by sonnyp** [comment]
réglé avec les nouveaux changements de restart et 

https://github.com/spotnik-ham/gui/commit/91aac697db8f852c7c1eed745b5d188439066c8a
https://github.com/spotnik-ham/gui/commit/4a11e39ef6624640894c5e157057d482378ad732
