### ISSUE TITLE
commandes inconnues webgui et dtmf

### ISSUE THREAD

**Issue by f5swb** [spotnik-ham/gui#17]
bonjour, 

10# Enable propagation monitor module
1# Enable parrot module
2# Enable EchoLink module
5# Enable Meta Information module
7# Enable FRN module                                                     
Commandes inconnues .... toutes les autres sont ok
doit-on être dans un mode spécial ?

**Comment by f5nlg** [comment]
hello
oui il faut etre dans un mode spécial , ou valider les modules , voir doc de svxlink
