### ISSUE TITLE
retarder le timer de retour au salon principal

### ISSUE THREAD

**Issue by f4gbv** [spotnik-ham/gui#18]
bonne question de F1EVM : peut-on retarder le timer de retour au salon RRF tant que l'on est en QSO sur le salon TEC, de manière à éviter les manips régulières en plein QSO TEC .

**Comment by f5swb** [comment]
Bonjour, de mon coté j'ai supprimé toutes les tempos de retour au salon principal.
Inconvénient : le relais restera sur le dernier salon activé.
Sinon il suffit d'éditer en SSH les fichiers .sh et d'allonger la durée de 20mn à 01h00 par exemple.
Cela permet d'assurer un retour automatique au salon principal. 
Le top serait d'avoir une fenêtre à cocher sur la webgui : maintien dans le salon ....
