### ISSUE TITLE
Annonce adresse ip par le GUI

### ISSUE THREAD

**Issue by ghost** [spotnik-ham/gui#22]
Bonjour,
Si on demande l'adresse IP dans le GUI, page keypad, il annonce 192,tiret,168,tiret,1,tiret......
au lieu de 192,point,168,point....
Aussi en anglais... 192,dash,168,dash....
Une petite manip de cosmetique...je vais chercher comment faire ,et si je trouve je te le publie ici
Hans F4VSJ

**Comment by f5nlg** [comment]
Hello
Tiret est dans les sons dash n'y est pas ...
C'est pour ça qu'il dit 192 tiret 168 etc ...

73"

**Comment by ghost** [comment]
Bonjour Jean-Philippe,
j'ai trouve le point...la frequence de ctcss il dit aussi 71 point 9...
il est dans "default" "decimal", on confond avec le virgule qu'on n'utilise pas dans chiffres au USA, c'est toujours 21.3 21 point 3...

alors j'ai changé de logic.tcl dans /usr/share/svxlink/event.d le process "sayIP"

`  proc sayIP {} {
    set result [exec /etc/spotnik/getIP]
    puts "$result"

    regexp "(\[0-9]{1,3})\.(\[0-9]{1,3})\.(\[0-9]{1,3})\.(\[0-9]{1,3})" $result all first second third fourth

    playSilence 100
    playNumber $first
    playSilence 100
    playMsg "default" "decimal"
    playSilence 100
    playNumber $second
    playSilence 100
    playMsg "default" "decimal"
    playSilence 100
    playNumber $third
    playSilence 100
    playMsg "default" "decimal"
    playSilence 100
    playNumber $fourth

    playSilence 500;
  }

`

et ca marche... 192 point 168 point...
Hans f4vsj

**Comment by f5nlg** [comment]
en français ça fait 192 décimal 168 etc .. décidément il va faloir faire un son en français 'Point'
