### ISSUE TITLE
Prise en compte du CTCSS sur le Spotnik Delta

### ISSUE THREAD

**Issue by armel** [spotnik-ham/gui#24]
Le paramétrage et la prise en compte du CTCSS sur le Spotnik Delta ne fonctionne pas à partir du GUI.
Il est préférable d'utiliser le script shell 818cli-prog présent sous /usr/local/sbin.
Editer la ligne 15 du script pour changer fréquence, CTCSS, etc. Attention à la programmation du code CTCSS. Voir la nomenclature dans le fichier README.txt présent lui aussi sous /usr/local/sbin.

**Comment by f4gbv** [comment]
ok, bug dans doc de sa818, inversion de rxct et txct
fichiers spotnik modifiés.
ok.
f4gbv:)
