### ISSUE TITLE
configuration de la radio module Delta 

### ISSUE THREAD

**Issue by f5nlg** [spotnik-ham/gui#7]
la config est faire en python avec 818-prog
https://github.com/echicken/node-dra818

**Comment by ghost** [comment]
Salut Jean Philippe,
ce ne serais pas possible de programmer le sa818 sur l'interface web, comme cela on aurais plus besoin d'acceder un terminal en ssh pour programmer une seule fois la frequence et ctcss sur le module.
Je pense surtout au utilisateurs de windoze...qui doivent installer putty pour y acceder une seule fois...
Biensur les spotnik que tu envoie sont preprogrammé, qui est une bonne idée.

Je pense que se ne serait pas mal sur la page configuration.
Mais une tres basse priorité pour moi, peut-etre la prochaine verion prevois déja...?
Hans f4vsj

**Comment by ghost** [comment]
Salut Jean Philippe,
J'ai trouvé une solution qui marche...pour le project des Neerlandais.Dans le fichier 818cli-prog j'ai mis la frequence et ctcss.
puis quand on boot le programme 818cli-prog est activé et programme la frequence...
Comme cela quelqu'un met la carte puce dans l'orange pi ,pour la premiere fois, boot et le 818 se mets en frequence connu. Apres le boot on accede le reseau automatique par la frequence connu avec un trx.Avec un reboot le 818cli-prog remets la frequence (initial)
hans
